# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('news', models.TextField()),
                ('src_name', models.CharField(blank=True, default='Anonymous', max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_img')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('news', models.TextField()),
                ('src_name', models.CharField(blank=True, default='Anonymous', max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_img')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NationalNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('news', models.TextField()),
                ('src_name', models.CharField(blank=True, default='Anonymous', max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_img')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('photo_desc', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='images/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='SlideModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slide_desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/slides')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SportsNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('news', models.TextField()),
                ('src_name', models.CharField(blank=True, default='Anonymous', max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news_img')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
