# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportsNewModel',
            new_name='InternationalNewsModel',
        ),
        migrations.RenameModel(
            old_name='LocalNewModel',
            new_name='LocalNewsModel',
        ),
        migrations.RenameModel(
            old_name='NationalNewModel',
            new_name='NationalNewsModel',
        ),
        migrations.RenameModel(
            old_name='InternationalNewModel',
            new_name='SportsNewsModel',
        ),
    ]
