# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0002_auto_20170820_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsnewsmodel',
            name='newstype',
            field=models.CharField(choices=[('SPORTS', 'Sports News'), ('LOCAL', 'Local News'), ('NATIONAL', 'National News'), ('INTERATIONAL', 'International News')], default='SPORTS', max_length=30),
        ),
    ]
