# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0003_sportsnewsmodel_newstype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportsNewsModel',
            new_name='NewsModel',
        ),
        migrations.DeleteModel(
            name='InternationalNewsModel',
        ),
        migrations.DeleteModel(
            name='LocalNewsModel',
        ),
        migrations.DeleteModel(
            name='NationalNewsModel',
        ),
    ]
