# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0004_auto_20170820_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='newstype',
            field=models.CharField(choices=[('SPORTS', 'Sports News'), ('LOCAL', 'Local News'), ('NATIONAL', 'National News'), ('INTERNATIONAL', 'International News')], default='SPORTS', max_length=30),
        ),
    ]
