# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0008_auto_20170829_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('profilepic', models.ImageField(upload_to='images/profiles')),
            ],
        ),
    ]
