# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0010_auto_20170829_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('video_desc', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='video_gallery')),
                ('uploaded_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='photosmodel',
            name='uploaded_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photosmodel',
            name='photo_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
