# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0012_videosmodel_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='schedules',
            field=models.ManyToManyField(to='fm_app.Schedule'),
        ),
    ]
