# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0013_auto_20170902_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='fm_app.Day'),
            preserve_default=False,
        ),
    ]
