# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0014_auto_20170902_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fm_app.Day'),
        ),
    ]
