# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0015_auto_20170902_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
