# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0016_remove_schedule_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
